### ISSUE TITLE
xmobar is hiding with position=Top on ppc64

### ISSUE THREAD

**Issue by clumens** [jaor/xmobar#264] opened 2016-04-29 14:54 UTC
Given the following xmobarrc:

Config { font = "xft:Droid Sans Mono:style=Bold:size=14"
       , border = BottomB
       , borderColor = "white"
       , bgColor = "grey15"
       , fgColor = "grey60"
       , position = Top
       , lowerOnStart = True
       , overrideRedirect = False
       , commands = [ Run StdinReader
                    , Run Com "/usr/libexec/xmobar/net" [] "net" 10
                    , Run Com "/usr/libexec/xmobar/power" [] "power" 10
                    , Run Weather "KBOS" ["-t","<tempC>C","-L","18","-H","25","--normal","green","--high","darkorange","--low","lightblue"] 36000
                    , Run Date "%a %b %e %r %Z" "date" 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% }{ %net% | %power% | %KBOS% | %date%"
       }       

xmobar is hiding at the top of the screen.  This same config works on x86_64.  Removing position=Top and adding position = TopSize L 100 20, textOffset = 15 fixes it.

The following picture shows what I mean when I say "hiding" - there's just a tiny bit of it way at the top:

![screenshot-25468](https://cloud.githubusercontent.com/assets/6717690/14919829/952b9ed0-0df8-11e6-938e-3c11c72d3024.jpg)

If you don't have access to hardware, perhaps you can direct me to where in the code you think things might be screwed up and I can take a look, test out patches, whatever.

**Comment by jaor** [comment] 2016-05-28 17:40
sorry for the late reply... i cannot reproduce it, but then, i don't
have a powerpc :) i'm not sure what could be making a difference, but
one quick thing to check is what happens if you set lowerInStart to
False?  and what about toggling overrideRedirect?

**Comment by jaor** [comment] 2022-02-25 01:54
closing, since no further feedback was provided and this is very old.  feel free to reopen.

**Closed by jaor** 2022-02-25 01:54 UTC
Labels: needs feedback
