### ISSUE TITLE
xmobar doesn't read config file

### ISSUE THREAD

**Issue by doenerkebap** [jaor/xmobar#412] opened 2019-11-22 20:45 UTC
I have my config file at `$XDG_CONFIG_HOME/xmobar/xmobarrc`, but xmobar does not read it if it is run without any options. It rather shows the default config with black background, date-time on the right in red, etc.

If i start xmobar with the file specified explicitly (`xmobar $XDG_CONFIG_HOME/xmobar/xmobarrc`) it works just fine.

xmobar v0.31

**Comment by jaor** [comment] 2019-11-23 00:38
it's working for me with current master.  any chance you could try with
that?

thanks.

**Comment by doenerkebap** [comment] 2019-11-25 18:56
I'm relatively new to  xmobar / haskell. Not sure if i installed latest master correctly. I did the following:
```
$ git clone git://github.com/jaor/xmobar
$ cd xmobar
$ stack install --flag xmobar:all_extensions
$ which xmobar
/home/doener/.local/bin/xmobar
$ xmobar --version
xmobar 0.32
```
Which looks correct to me.

But still, the behavior is the same:
Running just `xmobar` loads the default configuration. `xmobar $XDG_CONFIG_HOME/xmobar/xmobarrc
` loads the correct config.

**Comment by jaor** [comment] 2019-11-27 03:28
yes, that looks correct, but i still cannot reproduce the problem.  what
shell are you using? i guess something like

           env XDG_CONFIG_HOME=<value> xmobar

or, if you're using bash, simply

           XDG_CONFIG_HOME=<value> xmobar

also fails?

**Comment by pdobsan** [comment] 2019-12-10 21:00
If there is an empty `~/.xmobar/` directory, probably created silently by some previous version of the program, then xmobar bails out without reading the config file `$XDG_CONFIG_HOME/xmobar/xmobarrc` and just uses the default settings. So there still is some problem with dealing with the many possible config files.

Possibles fixes:
- Check for full path config files only and not for directories.
- Use only **one** config file `$XDG_CONFIG_HOME/xmobar/xmobarrc`, modulo the `XDG_CONFIG_HOME` environment variable.

I consider the second one a better solution than using many possible config files. A clear error/warning message, like _Can't find config file_ `$XDG_CONFIG_HOME/xmobar/xmobarrc` _, using default settings_ , could easily deal with backward compatibility issues.

**Comment by jaor** [comment] 2019-12-15 12:51
On Tue, Dec 10 2019, Peter Dobsan wrote:

> If there is an empty ~/.xmobar/ directory, probably created silently
> by some previous version of the program, then xmobar bails out without
> reading the config file $XDG_CONFIG_HOME/xmobar/xmobarrc and just uses
> the default settings. So there still is some problem with dealing with
> the many possible config files.
>
> Possibles fixes:
>
>   • Check for full path config files only and not for directories.
>   • Use only one config file $XDG_CONFIG_HOME/xmobar/xmobarrc, modulo the XDG_CONFIG_HOME environment
>     variable.
>
> I consider the second one a better solution than using many possible
> config files. A clear error/warning message, like Can't find config
> file $XDG_CONFIG_HOME/xmobar/xmobarrc , using default settings , could
> easily deal with backward compatibility issues.

i am not sure: some people start xmobar in ways that don't easily show
the console, and will just find themselves with a weird default
configuration.  so, while the first option is more convoluted, it might
be worth the trouble at this point...

**Comment by pdobsan** [comment] 2019-12-16 13:16
> i am not sure: some people start xmobar in ways that don't easily show the console, and will just find themselves with a weird default configuration.

I see your point, and also considered it myself. Unfortunately, that is a general problem with "self-assembled" desktop environments: there is no easy way too look for error messages of components started from `.xinitrc` and/or by the standalone window manger. I solve this problem using a simple init like system and capturing all components' `stdout/stderr` in separate log files.

> so, while the first option is more convoluted, it might be worth the trouble at this point...

Personally, I'd still prefer the second solution and cleaning up the config file situation once and for ever. Perhaps the default config could write the warning into the bar output so not to be missed by anybody. Just a thought.

**Comment by doenerkebap** [comment] 2019-12-22 01:54
Thanks @pdobsan, an empty `~/.xmobar/` was indeed the problem.

**Comment by jaor** [comment] 2020-08-07 14:25
i've implemented the option of looking for all possible config files,
not just directories.  closing.

**Closed** 2020-08-07 14:25 UTC
