### ISSUE TITLE
"Warning: Xmobar must be built with the with_xft flag to support font"

### ISSUE THREAD

**Issue by sebasijan** [jaor/xmobar#596] opened 2022-01-02 19:27 UTC
I am seeing the above error when trying to use any xft font

 I tried to reinstall with 

  > cabal install xmobar --flags="all_extensions" --reinstall

but it keeps telling me everything is already installed, so not sure what the problem is?

I can see this at the end of the output when installing:

        cabal: Error: some packages failed to install:
        alsa-core-0.5.0.1-5E1EqcYL2GWHtTsacKmWBR failed during the configure step. The
        exception was:
        ExitFailure 1
        alsa-mixer-0.3.0-BuC9fxPvOeO50fWjIji5Rg depends on alsa-mixer-0.3.0 which
        failed to install.
        xmobar-0.40-FtXeKImXj9C4gqk18vKgi1 depends on xmobar-0.40 which failed to
        install.

Although when I do a 

 > /home/bassie/.cabal/bin/xmobar --version

it gives me 

        xmobar 0.40
         (C) 2010 - 2020 Jose A Ortega Ruiz
         (C) 2007 - 2010 Andrea Rossato
         <mail@jao.io>

**Comment by guygastineau** [comment] 2022-02-05 18:25
Are you running `cabal install` from within this repo or is cabal fetching it from hackage?

**Comment by jaor** [comment] 2022-03-08 01:40
closing since no further input was provided and we cannot reproduce the problem.  please reopen as needed, thanks!

**Closed by jaor** 2022-03-08 01:40 UTC
Labels: needs feedback
