### ISSUE TITLE
QueueReader improvements

### ISSUE THREAD

**Issue by jsoo1** [jaor/xmobar#571] opened 2021-09-17 00:26 UTC
I started using the new QueueReader and it works pretty well save for a few issues:

- The documentation for the plugin could document what the item transformation function is for (the type signature is pretty clear, but still).
- The documentation should document what modules are being imported.
- The documentation should make clear that the alias for use in the template is defined when using Xmobar.QueueReader
- Using xmobar from other haskell code seems to have problems with the dbus module. Perhaps a more direct ipc can be created since using the QueueReader should be done from other Haskell code.
- Actions either don't work or I misunderstand how they should work when rendered directly from other haskell code.
- pp{Hidden,Urgent,Current,Visible} seem to not be updating immediately when I switch workspaces. Perhaps this is a lazy IO bug? Perhaps using [flushTQueue](https://hackage.haskell.org/package/stm-2.5.0.1/docs/Control-Concurrent-STM-TQueue.html#v:flushTQueue) could be used instead of readTQueue

Thanks!  So far it otherwise does exactly what it says on the label :)

**Comment by guygastineau** [comment] 2021-09-18 13:21
> The documentation for the plugin could document what the item transformation function is for (the type signature is pretty clear, but still).

Yeah, I guess I thought it was obvious, but that is the wrong mindset for the docs to have.  I should have added haddock comments for the fields of QueueReader too.

> Using xmobar from other haskell code seems to have problems with the dbus module. Perhaps a more direct ipc can be created since using the QueueReader should be done from other Haskell code.

This seems like an issue with the dubs plugin.  Nice catch though.

> Actions either don't work or I misunderstand how they should work when rendered directly from other haskell code.

I don't know what that means.

**Comment by guygastineau** [comment] 2021-09-18 13:50
> pp{Hidden,Urgent,Current,Visible} seem to not be updating immediately when I switch workspaces. Perhaps this is a lazy IO bug? Perhaps using flushTQueue could be used instead of readTQueue

Hmm, I am not experiencing this.if anything is in the queue it should be read by the plugin.  It is really hard to know why this is happening without reproduction.  Maybe you can share the driver code?

I `flushTQueue`  doesn't retry, and it will produce an empty list.  That require state to keep the latest string around.  Reading the internal code for `flushTQueue` I don't think it will force a write.  It just sticks the list together from the FIFO and sets the FIFO's lists to `[]`.

Also, readTQueue should block itself and retry indefinitely as a thread, so it should read new insertions in the queue as soon as the scheduler prioritizes it.  That assumes it is not somehow running behind xmonad.

 I think any issue solvable by flushing every read would be better solved using either a sized ring buffer or or a single TVar.

I don't think stm comes with a sized sing buffer, but it won't be very hard to make.  I am down to play with STM if you want to work with someone on it.

All that said, Iam  fine with parameterizing the q reading function for the plugin.  Users will need STM imported anyway.   That would make it simple for you to check if it makes a difference.

---

I am playing 3 music gigs today, so I won't have much time to think or correspond about this for most of the day.

**Comment by jsoo1** [comment] 2021-09-18 13:53
No problem. I won't forget about this but I will be traveling on vacation for the next week.

**Comment by guygastineau** [comment] 2021-09-18 13:56
@jsoo1 noted.  If you can post or link a minimal reproducible example before you go that would be stellar, but I understand if you don't have time.  Do you want to take point on the improvements and possible other STM plugins?  Otherwise I am likely to start playing with ideas.

**Comment by jsoo1** [comment] 2021-09-18 14:20
Sure. I think maybe some of my concurrency issues may have to do with distro/build systems not providing threaded rts options.  I'll be looking into it some. It's probably time I use a build script finally. I tried out making the tmvar for signals configurable (but only in other Haskell).

https://git.sr.ht/~jsoo/dotfiles/tree/release/item/xmonad/xmonad.hs

https://github.com/jsoo1/xmobar/tree/queuereader-improvements

**Comment by guygastineau** [comment] 2021-09-18 14:37
Cool. I'll take a look later.

Yeah, I use cabal via a build script for xmonad, and it is way nicer.

**Comment by liskin** [comment] 2021-09-20 07:32
The documentation for QueueReader should probably mention that a threaded RTS is necessary when used together with xmonad or any other program that makes blocking calls.

**Comment by guygastineau** [comment] 2021-09-20 19:39
Hmm, @liskin I was under the impression that xmobar in general needs the threaded RTS when used together with other haskell code.  If reading from a TQueue is stalled then the clock and other plugins would surely be stalled too.  Am I right?  I just mean, if it is true for xmobar in general then it should not be stated for each module.  Let me know if I am wrong, please.

**Comment by liskin** [comment] 2021-09-21 07:46
@guygastineau "when used together with other haskell code": but what "other Haskell code" could you use xmobar with before the introduction of QueueReader? Anyway, you're technically right that this is not an issue specific to QueueReader, and it's not even an issue specific to xmobar—the problem is in xmo**nad**. xmobar works just fine in a non-threaded-RTS, because it uses non-blocking Xlib calls. My thinking was that QueueReader is the right place for this cautionary note as it is the plugin that people are most likely to study whenever they try to integrate xmobar into another Haskell program like xmonad. And I think it's totally okay to actually name (and shame :-)) xmonad there, as it will probably be the most common usage scenario, so being specific and explanatory makes sense.

**Comment by jsoo1** [comment] 2021-09-26 03:45
Hi, back from vacation.  Yes, I can confirm that using the threaded rts options fixes all the issues with blocking calls.  I do think that the RTS options should be mentioned in places where the user would be integrating with haskell code.

**Comment by guygastineau** [comment] 2021-10-03 03:39
> @guygastineau "when used together with other haskell code": but what "other Haskell code" could you use xmobar with before the introduction of QueueReader? Anyway, you're technically right that this is not an issue specific to QueueReader, and it's not even an issue specific to xmobar—the problem is in xmo**nad**. xmo**bar** works just fine in a non-threaded-RTS, because it uses non-blocking Xlib calls. My thinking was that QueueReader is the right place for this cautionary note as it is the plugin that people are most likely to study whenever they try to integrate xmobar into another Haskell program like xmonad. And I think it's totally okay to actually name (and shame :-)) xmonad there, as it will probably be the most common usage scenario, so being specific and explanatory makes sense.

I think some people are using the plugins from the [Pipe-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#pipe-based-logging) section of the docs for intra-process communication although those plugins are not limited to such use cases.  Otherwise, the (largely unused?) [HandleReader](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#handlereader-handle-alias) is the original `just-useful-from-other-haskell` plugin as far as I can tell.

I think the caveat then belongs to 3 sections [Pipe-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#pipe-based-logging), [Handle-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#handle-based-logging), and [Software Stransactional-Memory](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#software-transactional-memory).  I try avoiding redundancy probably to a fault.  Maybe we should add a caveat to all three of these sections?

> Hmm, @liskin I was under the impression that xmobar in general needs the threaded RTS when used together with other haskell code.

Here I meant, I thought `initThreads` was from `Xmobar`, but I just discovered it is from [X11](https://hackage.haskell.org/package/X11-1.10.1/docs/Graphics-X11-Xlib-Misc.html#g:7).  I thought it would require the threaded RTS, but I am obviously wrong.

**Comment by guygastineau** [comment] 2021-10-03 03:41
Thank you both for staying on this!  I am prone to long absences from my open source contributions :/

**Comment by liskin** [comment] 2022-02-20 19:18
@guygastineau
> I think the caveat then belongs to 3 sections [Pipe-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#pipe-based-logging), [Handle-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#handle-based-logging), and [Software Stransactional-Memory](https://github.com/jaor/xmobar/blob/master/doc/plugins.org#software-transactional-memory). I try avoiding redundancy probably to a fault. Maybe we should add a caveat to all three of these sections?

Not really, the [Handle-Based Logging](https://github.com/jaor/xmobar/blob/master/doc/window-managers.org#handle-based-logging) example uses `forkProcess` which is an actual POSIX fork(2), so it's irrelevant whether the parent xmonad process is using a threaded RTS or not. (It is, however, still important that the parent either calls `initThreads` or doesn't make any Xlib calls prior to `forkProcess`.)

Therefore I think it's fine to just add a paragraph to the STM/QueueReader section.

@jaor
> i agree it'd be useful to mention this problem in QueueReader's documentation: would you have time to suggest a little paragraph to that effect?

I'll open a PR today.

**Comment by liskin** [comment] 2022-02-20 19:58
Here: https://github.com/jaor/xmobar/pull/611

**Comment by jaor** [comment] 2022-02-20 23:33
excellent, PR merged.  i'm therefore closing this issue, but feel free
to re-open if there's still anything left.

**Closed** 2022-02-20 23:33 UTC
