### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jneen** [jaor/xmobar#322] opened 2017-12-02 13:43 UTC
Unlike #310, I am still experiencing this with ghc 8.2.1. It seems to usually be triggered around the time my workrave installation goes into break mode, although I have a hard time seeing how that would be relevant. I'm happy to gather more data, but not sure where to start with this sort of thing.

```
Dec 02 22:36:17 rosemary kernel: xmobar[25683]: segfault at 4 ip 00007ff2e23a6cd2 sp 00007ffc3e998d70 error 
Dec 02 22:36:17 rosemary systemd[1]: Started Process Core Dump (PID 29864/UID 0).
Dec 02 22:36:18 rosemary systemd-coredump[29865]: Process 25683 (xmobar) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 25683:
                                                  #0  0x00007ff2e23a6cd2 n/a (libHSrts-ghc8.2.1.so)
                                                  #1  0x00007ff2e23b9e1c n/a (libHSrts-ghc8.2.1.so)
                                                  #2  0x00007ff2e23ba878 n/a (libHSrts-ghc8.2.1.so)
                                                  #3  0x00007ff2e23bb8f0 n/a (libHSrts-ghc8.2.1.so)
                                                  #4  0x00007ff2e23c1fba n/a (libHSrts-ghc8.2.1.so)
                                                  #5  0x00007ff2e23b436d StgReturn (libHSrts-ghc8.2.1.so)
                                                  #6  0x00007ff2e23b4ede scheduleWaitThread (libHSrts-ghc8.2
                                                  #7  0x00007ff2e23b789e hs_main (libHSrts-ghc8.2.1.so)
                                                  #8  0x0000000000585821 n/a (xmobar)
                                                  #9  0x00007ff2e1534f6a __libc_start_main (libc.so.6)
                                                  #10 0x000000000042e9ea n/a (xmobar)
```

**Comment by jneen** [comment] 2017-12-02 13:46
Standard info dump:

```
[ jneen@rosemary ~ ] $ 
; uname -a
Linux rosemary 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux

[ jneen@rosemary ~ ] $ 
; xmobar --version
Fields missing from config defaulted: additionalFonts,bgColor,fgColor,sepChar,alignSep,border,borderColor,position,textOffset,iconOffset,allDesktops,overrideRedirect,pickBroadest,hideOnStart,lowerOnStart,persistent,iconRoot,alpha
xmobar 0.24.5
 (C) 2007 - 2010 Andrea Rossato 
 (C) 2010 - 2017 Jose A Ortega Ruiz
 <xmobar@projects.haskell.org>

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the License for more details.

[ jneen@rosemary ~ ] $ 
; cat .xmobarrc 
Config
  { commands = [ Run StdinReader,
                 Run Com "date" [] "" 10,
                 Run Com "xmobar-dropbox" [] "" 30,
                 Run Memory [] 10,
                 Run Battery [] 100,
                 Run Cpu [] 10 ]
  , template = "%StdinReader% %date% }{ dropbox: %xmobar-dropbox% | <fc=#AAAA00>%battery%</fc> | %memory% | %cpu%"
  , font = "xft:InputMono-12,M+ 2c-12,Symbola-10" }

[ jneen@rosemary ~ ] $ 
; xmonad --version
xmonad 0.13

```

**Comment by dschrempf** [comment] 2018-05-29 13:23
I wanted to add that this is now also effecting me once in a while. I am also Arch user and the other bug was somehow also related to the Arch Haskell stack...
                                                    
                                                    Stack trace of thread 744:
                                                    #0  0x00007f5e22183248 n/a (libHSrts-ghc8.4.2.so)
                                                    #1  0x00007f5e2218256d n/a (libHSrts-ghc8.4.2.so)
                                                    #2  0x00007f5e22199334 n/a (libHSrts-ghc8.4.2.so)
                                                    #3  0x00007f5e2219fbbb n/a (libHSrts-ghc8.4.2.so)
                                                    #4  0x00007f5e2218a12d n/a (libHSrts-ghc8.4.2.so)
                                                    #5  0x00007f5e2218ae2a scheduleWaitThread (libHSrts-ghc8.4.2.so)
                                                    #6  0x00007f5e22194cfc hs_main (libHSrts-ghc8.4.2.so)
                                                    #7  0x000000000058acff n/a (xmobar)
                                                    #8  0x00007f5e2187b06b __libc_start_main (libc.so.6)
                                                    #9  0x000000000042ffba n/a (xmobar)

**Comment by miyalys** [comment] 2018-07-09 15:49
Also experiencing xmobar crashes. I'm also use arch - and xmonad.
As far as I recall, it disappeared once I removed/commented StdinReader, so the issue might be related to the input xmobar receives from xmonad.

$ dmesg | grep xmobar:

> [ 2442.250994] xmobar[655]: segfault at fffffffffffffff8 ip 00007f65b0ace2b8 sp 00007ffe5cfe7d40 error 5 in libHSrts-ghc8.4.3.so[7f65b0ab4000+5f000]
> [13510.951588] xmobar[10176]: segfault at 1a000003c0 ip 00007fd91be6fce0 sp 00007ffe5f65b2e8 error 4 in libHSbase-4.11.1.0-ghc8.4.3.so[7fd91b69a000+8d0000]

**Comment by jaor** [comment] 2018-07-16 16:08
if that's the cause, a workaround would be to use an X property instead
of stdin... https://github.com/jaor/xmobar#xpropertylog-propname

(i use it with sawfish, and that might explain why i've never seen these
crashes)

**Comment by jaor** [comment] 2018-10-06 16:18
This is most probably due to the GHC bugs discussed at length in #354 and #355, fixed in recent GHC versions, so i am closing this one.  Please, reopen if this is still a problem . Thanks!

**Closed** 2018-10-06 16:19 UTC

**Comment by filterfish** [comment] 2019-02-13 04:37
Just to let you know that before I recompiled xmobar with ghc 8.6.2 it was segfaulting every time I connected or disconnected my external monitor—in fact it would often take multiple goes to restart it. And after recompiling it, it hasn't segfaulted once.

So I think it's safe to say it's fixed!
