### ISSUE TITLE
Support use of pango instead of Xft to render text

### ISSUE THREAD

**Issue by jktomer** [jaor/xmobar#389] opened 2019-05-03 16:51 UTC
xmobar crashes (see X error below) when attempting to render glyphs from color emoji fonts. This appears to be due to a lack of support in Xft itself: see https://bugzilla.redhat.com/show_bug.cgi?id=1498269#c1

The solution is apparently to use a newer rendering library such as Pango.

I am happy to contribute an implementation but don't have one ready yet; opening this bug to track the feature.

X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  58
  Current serial number in output stream:  87

**Comment by jaor** [comment] 2019-05-03 22:50
Thanks.  Your contribution would be greatly appreciated.  I've read
critiques against Pango in some contexts, but i have never really looked
seriously into it, so i'm at least neutral (and when i think on how
little i like using Xft, and the many problems it's given me, i cannot
imagine Pango being any worse!).

**Comment by jaor** [comment] 2022-03-01 14:35
@rhysday yes, i think so

**Comment by jaor** [comment] 2022-03-01 14:37
marking this one as a duplicate of #572, where we can track any
progress on this (much desired!) feature.

**Closed** 2022-03-01 14:37 UTC
Labels: feature request
