### ISSUE TITLE
Core temp file not present

### ISSUE THREAD

**Issue by chrissound** [jaor/xmobar#291] opened 2017-02-27 16:36 UTC
```
ls /sys/bus/platform/devices/coretemp                      
ls: cannot access '/sys/bus/platform/devices/coretemp': No such file or directory
```

This file is present however (with the correct value) /sys/class/hwmon/hwmon0/device/hwmon/hwmon0/temp1_input

**Comment by jaor** [comment] 2017-02-28 15:59
On Mon, Feb 27 2017, Chris Stryczynski wrote:

> ls /sys/bus/platform/devices/coretemp                      
> ls: cannot access '/sys/bus/platform/devices/coretemp': No such file or directory

what should be there is not coretemp, but coretemp.0, etc.  is that
directory empty for you?

**Comment by chrissound** [comment] 2017-03-01 18:27
```
ls -l /sys/bus/platform/devices
total 0
lrwxrwxrwx 1 root root 0 Mar  1 10:01  alarmtimer -> ../../../devices/platform/alarmtimer
lrwxrwxrwx 1 root root 0 Mar  1 10:01  ATK0110:00 -> ../../../devices/pci0000:00/0000:00:14.3/ATK0110:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  i8042 -> ../../../devices/platform/i8042
lrwxrwxrwx 1 root root 0 Mar  1 10:01  microcode -> ../../../devices/platform/microcode
lrwxrwxrwx 1 root root 0 Mar  1 10:01  pcspkr -> ../../../devices/platform/pcspkr
lrwxrwxrwx 1 root root 0 Mar  1 10:01  PNP0103:00 -> ../../../devices/pci0000:00/0000:00:14.3/PNP0103:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  PNP0800:00 -> ../../../devices/pci0000:00/0000:00:14.3/PNP0800:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  PNP0C04:00 -> ../../../devices/pci0000:00/0000:00:14.3/PNP0C04:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  PNP0C0C:00 -> ../../../devices/platform/PNP0C0C:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  PNP0C14:00 -> ../../../devices/platform/PNP0C14:00
lrwxrwxrwx 1 root root 0 Mar  1 10:01  regulatory.0 -> ../../../devices/platform/regulatory.0
lrwxrwxrwx 1 root root 0 Mar  1 10:01  serial8250 -> ../../../devices/platform/serial8250
lrwxrwxrwx 1 root root 0 Mar  1 10:01 'SP5100 TCO timer' -> '../../../devices/platform/SP5100 TCO timer'
lrwxrwxrwx 1 root root 0 Mar  1 10:01  vboxdrv.0 -> ../../../devices/platform/vboxdrv.0
lrwxrwxrwx 1 root root 0 Mar  1 10:01  vesa-framebuffer.0 -> ../../../devices/platform/vesa-framebuffer.0
```

So no that does not appear there either.

**Comment by jaor** [comment] 2017-03-03 01:33
i see.  i've just pushed a patch to master that tries to address the
issue... i cannot really check whether it works, since in my system the
directory you mention doesn't exist: would you please give it a shot if
you have the opportunity? thanks a lot!

**Comment by chrissound** [comment] 2017-03-03 14:20
Hmmm so I'm getting `error: Prelude.read: no parse` in the temperature slot.

```
$ cat /sys/class/hwmon/hwmon0/device/hwmon/hwmon0/temp1_input
31000
```

**Comment by jaor** [comment] 2017-03-04 18:02
On Fri, Mar 03 2017, Chris Stryczynski wrote:

> Hmmm so I'm getting error: Prelude.read: no parse in the temperature slot.
>
> $ cat /sys/class/hwmon/hwmon0/device/hwmon/hwmon0/temp1_input
> 31000

hmmm... do you have a
/sys/class/hwmon/hwmon0/device/hwmon/hwmon0/temp1_label file too?

**Comment by chrissound** [comment] 2017-03-06 11:38
I do:
```
cat /sys/class/hwmon/hwmon0/device/hwmon/hwmon0/temp1_label    
CPU Temperature
```

**Comment by jaor** [comment] 2017-03-20 16:29
sorry i took so long to answer (real life intrusions!).  i don't have an
explanation yet for what's going on... i've tried with similar paths
(created by hand, since my kernel doesn't populate those /sys/class),
and they seem to work... please let me give it another try when i
can... thanks!

**Comment by chrissound** [comment] 2017-03-20 18:51
Could I call the corresponding function from GHCi? Might be able to track it down then.

I'm not sure which function it is though?

**Comment by jaor** [comment] 2017-05-03 17:24
sorry @chrissound, i lost track of this one.

the function reading the files is checkDataRetrieval, which is called in src/Plugins/Monitors/CoreTemp.hs with a collection of path components. checkDataRetrieval is defined Plugins.Monitors.CoreCommon.

**Comment by peterbecich** [comment] 2017-06-05 17:41
Almost the same for me
```
  /sys/bus/platform/devices:
  total 0
  drwxr-xr-x 2 root root 0 Jun  5 10:32 .
  drwxr-xr-x 4 root root 0 Jun  4 21:11 ..
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 alarmtimer -> ../../../devices/platform/alarmtimer
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 AMDI0030:00 -> ../../../devices/platform/AMDI0030:00
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 AMDIF030:00 -> ../../../devices/platform/AMDIF030:00
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 i8042 -> ../../../devices/platform/i8042
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 microcode -> ../../../devices/platform/microcode
  lrwxrwxrwx 1 root root 0 Jun  5 10:32 nct6775.656 -> ../../../devices/platform/nct6775.656
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 pcspkr -> ../../../devices/platform/pcspkr
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 platform-framebuffer.0 -> ../../../devices/platform/platform-framebuffer.0
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 PNP0103:00 -> ../../../devices/platform/PNP0103:00
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 PNP0800:00 -> ../../../devices/pci0000:00/0000:00:14.3/PNP0800:00
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 PNP0C0C:00 -> ../../../devices/platform/PNP0C0C:00
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 PNP0C14:00 -> ../../../devices/platform/PNP0C14:00
  lrwxrwxrwx 1 root root 0 Jun  5 10:32 regulatory.0 -> ../../../devices/platform/regulatory.0
  lrwxrwxrwx 1 root root 0 Jun  4 21:11 serial8250 -> ../../../devices/platform/serial8250
  lrwxrwxrwx 1 root root 0 Jun  5 10:32 SP5100 TCO timer -> ../../../devices/platform/SP5100 TCO timer
```

`temp1`, `temp2`, etc correspond to different things for me than for @chrissound 

```

/sys/class/hwmon/hwmon0/device/hwmon/hwmon0 $ cat temp1_label
SYSTIN
/sys/class/hwmon/hwmon0/device/hwmon/hwmon0 $ cat temp2_label
CPUTIN
/sys/class/hwmon/hwmon0/device/hwmon/hwmon0 $ cat temp3_label
AUXTIN0
```

Thanks!

**Comment by peterbecich** [comment] 2017-06-07 18:32
I suspect this is my issue: https://askubuntu.com/questions/912413/is-there-a-temperature-sensing-utility-for-linux-that-will-read-a-ryzen-1700-cpu

Reading the core temps in xmobar worked easily on my old computer.  For me the problem is not xmobar.  Thanks!

**Comment by jaor** [comment] 2017-06-07 22:03
@peterbecich thanks a lot for the update. @chrissound could this be also the problem for you?

**Comment by chrissound** [comment] 2017-06-07 22:10
Hmm, so I am using an AMD cpu (FX 8320). But the temperature shows up correctly using lm_sensors.

**Comment by peterbecich** [comment] 2017-06-07 23:35
@chrissound we must have different problems then.  I will try the Ask Ubuntu solution now and report back.

No core temps for me, excluding CPUTIN which I've read is the mobo's temperature reading of the CPU:

```
peterbecich@Neptune:~$ sensors
nct6779-isa-0290
Adapter: ISA adapter
in0:                    +0.62 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +0.26 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                    +3.34 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                    +3.34 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                    +1.82 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +0.90 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +0.28 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                    +3.47 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                    +3.26 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)
in10:                   +0.23 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +1.04 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +1.68 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +1.05 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +1.81 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                  1112 RPM  (min =    0 RPM)
fan2:                  1854 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +26.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +29.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                +82.0°C    sensor = thermistor
AUXTIN1:                +99.0°C    sensor = thermistor
AUXTIN2:                +24.0°C    sensor = thermistor
AUXTIN3:                -23.0°C    sensor = thermistor
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
PCH_MCH_TEMP:            +0.0°C  
intrusion0:            OK
intrusion1:            ALARM
beep_enable:           disabled
```

**Comment by nicolasavru** [comment] 2017-08-26 20:03
https://github.com/jaor/xmobar/commit/938a8d8307c1c4794c5fcf269c587c3c5c5e70df broke cpu temp monitoring for me (I get `error: Prelude.read: no parse`). https://github.com/jaor/xmobar/blob/a7bc612666062b5c48efae74054a453334727e91/src/Plugins/Monitors/CoreTemp.hs#L43 assumes that every sensor label ends with a number.
This is true for coretemp (hwmon0 corresponds to coretemp on my system):
```
[15:29:04][avru@gateway:~]$ cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/*_label
Package id 0
Core 0
Core 1
Core 2
Core 3
Core 4
Core 5
[15:29:08][avru@gateway:~]$ cat /sys/class/hwmon/hwmon0/*_label
Package id 0
Core 0
Core 1
Core 2
Core 3
Core 4
```
This is not true for other sensors:
```
[15:29:12][avru@gateway:~]$ cat /sys/class/hwmon/hwmon1/*_label
SYSTIN
CPUTIN
AUXTIN0
AUXTIN1
AUXTIN2
AUXTIN3
PECI Agent 0
PCH_CHIP_CPU_MAX_TEMP
PCH_CHIP_TEMP
PCH_CPU_TEMP
```
When lbl tries to parse most of those strings, it tries to `read` the empty string it gets from `dropWhile (not . isDigit)` and throws `Prelude.read: no parse`.

The coretemp kernel module only applies to Intel CPUs (AMD CPUs use different sensors, don't know which offhand), which would explain the missing /sys/bus/platform/devices/coretemp dir in the original bug report. /sys/class/hwmon/... contains all sorts of sensors (including CPU temps), so having xmobar look at everything in there isn't correct. I doubt that looking at just /sys/class/hwmon/hwmon0/... is correct either since (I think) the CPU sensors aren't necessarily on hwmon0.

If you wish to be able to monitor non-coretemp temp sensors, a good approach may be to change the template spec to allow arbitrary labels that would match the *_label files. This would be useful for coretemp sensors also: on my system, given the current parsing, <core0> corresponds to the "Package id 0" sensor, <core1> to "Core 0", <core2> to "Core 1", and so on. May be worth leaving the current <coreN> template syntax for backward-compatibility.

Full sensors output from my system:
```
[15:24:27][avru@gateway:/tmp/xmobar]$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +37.0°C  (high = +95.0°C, crit = +105.0°C)
Core 0:        +32.0°C  (high = +95.0°C, crit = +105.0°C)
Core 1:        +30.0°C  (high = +95.0°C, crit = +105.0°C)
Core 2:        +31.0°C  (high = +95.0°C, crit = +105.0°C)
Core 3:        +32.0°C  (high = +95.0°C, crit = +105.0°C)
Core 4:        +28.0°C  (high = +95.0°C, crit = +105.0°C)
Core 5:        +32.0°C  (high = +95.0°C, crit = +105.0°C)

nct6791-isa-0290
Adapter: ISA adapter
Vcore:                  +0.86 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +1.84 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                   +3.30 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                  +3.30 V  (min =  +2.98 V, max =  +3.63 V)
in4:                    +1.25 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +1.67 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +0.26 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                   +3.49 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                   +3.33 V  (min =  +2.70 V, max =  +3.63 V)
in9:                    +1.06 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +1.65 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +0.35 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +1.25 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +1.05 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +0.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                  1053 RPM  (min =    0 RPM)
fan2:                  2347 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                   929 RPM  (min =    0 RPM)
fan5:                   869 RPM  (min =    0 RPM)
fan6:                     0 RPM
SYSTIN:                 +37.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +31.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                +89.0°C    sensor = thermistor
AUXTIN1:                +35.0°C    sensor = thermistor
AUXTIN2:                +80.0°C    sensor = thermistor
AUXTIN3:               +127.0°C    sensor = thermistor
PECI Agent 0:           +36.5°C  (high = +80.0°C, hyst = +75.0°C)
                                 (crit = +105.0°C)
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled
```

**Comment by jaor** [comment] 2017-09-02 18:26
thanks a lot for the detailed information, Nicolas.  i'll give a more
robust implementation a shot when i find some time (or someone else does!).

**Comment by ptkato** [comment] 2018-08-20 18:55
Any news on this? My files are also in another folder. Should I symlink them? If so, which ones and to where?

**Comment by jaor** [comment] 2018-10-10 02:03
@ptkato sorry for the awfully late reply, your question went totally under my radar.  By default, CoreTemp is looking for directories inside `/sys/class/hwmon/`, which are in my system symlinks called `hwmon0`, `hwmon1`, and so on.  An alternative place it looks into is `/sys/bus/platform/devices/coretemp.n/hwmon/hwmon/`.  Inside there it's expecting files called `temp1_input`, `temp1_label`, and so on.

**Comment by jaor** [comment] 2018-10-10 02:15
@nicolasavru i've reverted 938a8d8, since it wasn't actually helping in any way. @ptkato that means that the directory that it's being looked for is the /sys/bus one...  we still need a proper fix for the problems described by @nicolasavru .

**Comment by jaor** [comment] 2020-06-26 23:39
this should, at long last, be fixed in recent releases, starting with
0.35.

please, feel free to re-open otherwise.

**Closed** 2020-06-26 23:40 UTC
Labels: bug
