### ISSUE TITLE
Failed to build latest xmobar 0.37

### ISSUE THREAD

**Issue by lebensterben** [jaor/xmobar#513] opened 2020-12-02 09:48 UTC
Failed to build `xmobar` 0.37 with GHC 8.8.4
`cabal install xmobar --flags="all_extensions"`

> Failed to build exe:c2hs from c2hs-0.28.6.
Build log (
/home/lucius/.cabal/logs/ghc-8.8.4/c2hs-0.28.6-db04b218ca0186503bf16e119ffe384f2f5425d4d9d8c61a3703ac43d0176766.log
):
Configuring executable 'c2hs' for c2hs-0.28.6..
Preprocessing executable 'c2hs' for c2hs-0.28.6..
Building executable 'c2hs' for c2hs-0.28.6..
>
>src/C2HS/C/Names.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘C2HS.C.Names’
  |
1 | --  C->Haskell Compiler: C name analysis
  | ^
>
>src/C2HS/C/Trav.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘C2HS.C.Trav’
  |
1 | --  C->Haskell Compiler: traversals of C structure tree
  | ^
>
>src/C2HS/Gen/Header.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘C2HS.Gen.Header’
  |
1 | --  C->Haskell Compiler: custom header generator
  | ^
cabal: Failed to build exe:c2hs from c2hs-0.28.6 (which is required by
exe:xmobar from xmobar-0.36). See the build log above for details.

**Comment by lebensterben** [comment] 2020-12-02 09:53
This is related to https://github.com/haskell/c2hs/issues/260

**Comment by jaor** [comment] 2020-12-02 17:40
this seems an error building c2hs, before even starting with xmobar's
code, so i'm not sure we can help here?  maybe a bug report to c2hs
would be in order?

**Comment by jaor** [comment] 2020-12-02 17:41
(marking as a duplicate of #260, please follow up there.  thanks!)

**Closed by jaor** 2020-12-02 17:41 UTC
