### ISSUE TITLE
Alsa: stray processes & high CPU on restart/logout

### ISSUE THREAD

**Issue by ivanbrennan** [jaor/xmobar#432] opened 2020-02-29 20:37 UTC
When xmonad is restarted, the Alsa plugin is starting a new `alsactl` process but not cleaning up the existing one. This leads to an accumulation of processes over a series of restarts.

Furthermore, logging out causes these processes to change from "interruptible sleep" to active polling, leading to high CPU usage.

---

Initially (first login after a reboot), there's one `alsactl` process in an "interruptible sleep" (`S`) state.
```
$ ps axo pid,state,command | awk 'NR==1 || /alsactl monitor default$/'
  PID S COMMAND
 1296 S /run/current-system/sw/bin/alsactl monitor default
```
Each `xmonad --restart` creates a new `alsactl` process.
```
$ xmonad --restart

$ ps axo pid,state,command | awk 'NR==1 || /alsactl monitor default$/'
  PID S COMMAND
 1296 S /run/current-system/sw/bin/alsactl monitor default
 1697 S /run/current-system/sw/bin/alsactl monitor default

$ xmonad --restart

$ ps axo pid,state,command | awk 'NR==1 || /alsactl monitor default$/'
  PID S COMMAND
 1296 S /run/current-system/sw/bin/alsactl monitor default
 1697 S /run/current-system/sw/bin/alsactl monitor default
 1729 S /run/current-system/sw/bin/alsactl monitor default
```

Exiting xmonad changes the processes state to `R` (actively running). I ran the following from a linux console to rule out any interaction with login/X/xmonad/etc.
```
$ ps axo pid,state,command | awk 'NR==1 || /alsactl monitor default$/'
  PID S COMMAND
 1296 R /run/current-system/sw/bin/alsactl monitor default
 1697 R /run/current-system/sw/bin/alsactl monitor default
 1729 R /run/current-system/sw/bin/alsactl monitor default
```

Running `strace` on any of these processes show an endless stream of polling:
```
epoll_wait(5, [{EPOLLIN, {u32=34444016, u64=34444016}}], 1, 200) = 1
```

---

I was hacking on my xmonad.hs, had recompiled and restarted xmonad several times, and when I logged out (and back in), noticed a jump in CPU.

My current workaround is to add the following to my `startupHook`
```haskell
spawn "ps axo pid,s,command | awk '/alsactl monitor default$/' | xargs --no-run-if-empty kill"
```

**Comment by slotThe** [comment] 2020-05-19 13:04
For what its worth, the plugin *does* seem to clean up after itself, just that it only does so *after* the volume has been updated.  I.e. if you restart xmonad there are indeed multiple `alsactl` processes running, but when you change the volume all of these but the active process seem to be killed.

I couldn't reproduce the second issue you're talking about (my state continues to be `S`, even though the X server was killed).

**Comment by jaor** [comment] 2020-05-19 18:20
On Tue, May 19 2020, slotThe wrote:

> For what its worth, the plugin does seem to clean up after itself,
> just that it only does so after the volume has been updated. I.e. if
> you restart xmonad there are indeed multiple alsactl processes
> running, but when you change the volume all of these but the active
> process seem to be killed.

That's however suboptimal.  In my use case, for instance, it's not
uncommon that i don't change the volume in months (i change that of the
connected equipment), but might restart xmobar hundreds of
times... having processes there waiting for me to change the volume to
disappear is a bit ugly, no?

**Comment by slotThe** [comment] 2020-05-20 20:00
On Tue, May 19 2020 20:21, jao wrote:
> having processes there waiting for me to change the volume to
> disappear is a bit ugly, no?

Oh don't get me wrong, I definitely agree that this should be fixed;
sorry if that wasn't clear.  I played around with the code a bit today,
but could not get any sensible result out of it.  I'll probably revisit
it at some point, should not someone else swoop in and fix it before
that.

**Comment by danyeet** [comment] 2021-02-25 20:11
I also get many alsactl processes when I restart pulse's or pipewire's unit services. Glad this issue is reported, hope a fix is coming soon one way or the other.

**Comment by jaor** [comment] 2022-07-10 01:08
moved to https://codeberg.org/jao/xmobar/issues/432

**Closed by jaor** 2022-07-10 01:08 UTC
