### ISSUE TITLE
Vertical text alignment broken (again)

### ISSUE THREAD

**Issue by twesterhout** [jaor/xmobar#317] opened 2017-09-25 20:19 UTC
So I've compiled `xmobar 0.24.5` to use xft fonts. The result, however, is not very good:
![textoffset](https://user-images.githubusercontent.com/14264576/30828357-c156ebe2-a23d-11e7-9253-dfdac75a7de2.png)
One can clearly see (I've added some space above the bar for clarity) that there's something wrong with text alignment. The picture also shows my current configuration.

Let me know if there's anything I can do to help.

**Comment by jaor** [comment] 2017-09-25 22:32
when you say "again," is it because a previous version of xmobar with
the same configuration was working better? also, you seem to be using
multiple fonts: is "something wrong" with all of them? thanks

**Comment by twesterhout** [comment] 2017-09-26 06:04
Last version of xmobar I had installed was compiled without `with_xft` flag, so I can't test whether this behavior is `0.24.5` specific (On second thought, I could try and compile `0.23` if you'd like to see the comparison). As for multiple fonts, misalignment only occurs for Xft fonts.

**Comment by jaor** [comment] 2017-09-26 22:13
On Tue, Sep 26 2017, Tom Westerhout wrote:

> Last version of xmobar I had installed was compiled without with_xft
> flag, so I can't test whether this behavior is 0.24.5 specific (On
> second thought, I could try and compile 0.23 if you'd like to see the
> comparison). As for multiple fonts, misalignment only occurs for Xft
> fonts.

but does it occur when you only use a single xft font?

**Comment by twesterhout** [comment] 2017-09-26 22:29
No, it does not. Although very nice, it'd still like to see multiple fonts working.

**Comment by jaor** [comment] 2017-09-26 22:44
yes, i'd also like to see multiple fonts working.  is it possible that
the problem is only present when we mix xft and non-xft faces?

**Comment by twesterhout** [comment] 2017-09-27 05:09
No, I believe I've tried both Xft + Xft and Xft + non-Xft. It's interesting that if I make the second font smaller than the primary one, text is shifted more to the bottom (as opposed to what I've shown above).

So my guess is that text written in the second font picks the alignment of the first one. For example here [Main.hs#L69](https://github.com/jaor/xmobar/blob/master/src/Main.hs#L69) I see that `font` I specify in the `Config` is indeed the first. But then here [Xmobar.hs#L350](https://github.com/jaor/xmobar/blob/master/src/Xmobar.hs#L350) only the first element is used. Don't take this guess too seriously though, I'm only starting with Haskell.

**Comment by jaor** [comment] 2018-07-16 16:02
hi... i haven't fixed these problems specifically, but at least now
(since version 0.27) we can provide independent vertical offsets for
each the fonts usinng `textOffset` and `textOffsets`.  hope that helps a
bit.

**Comment by jaor** [comment] 2022-02-25 01:52
closing, since a solution was provided.

**Closed by jaor** 2022-02-25 01:52 UTC
