### ISSUE TITLE
Invalid configuration file unexpected "s"

### ISSUE THREAD

**Issue by vividsystem** [jaor/xmobar#528] opened 2021-03-11 17:48 UTC
My Configuration file
```
Config {
  font = "xft:mononoki-Regular Nerd Font Complete Mono:weight=bold:pixelsize=12:antialias=true:hinting=tr>
    , additionalFonts = []
       , borderColor = "black"
       , border = TopB
       , bgColor = "#282c34"
       , fgColor = "#ff6c6b"
       , alpha = 255
       , position = Static {xpos = 0, ypos = 0, width = 1920, height = 24}
       , lowerOnStart = True
       , persistent = True
       , hideOnStart = False
       , allDesktops = True
       , overrideRedirect = True
       , iconRoot = "." --defaults: "."
       , commands = [
                    -- NETWORK Up & Downstream
                      Run Network "wlp0s20u4" [
                      "-t",
                      "\uf0ab <rx>kb \uf0aa <tx>kb"
                      ] 20

                    -- DATE
                  , Run Date " %b %d %Y - (%H:%M:%S) " "date" 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%date% <fc=#666666>|</fc> %wlp0s20u4%"
       }
```

The error i get:
```
xmobar --verbose /home/ms/.config/xmobar/xmobarrc
Invalid configuration file: "Config" (line 26, column 10):
unexpected "s"
expecting space or "Run"

(No compilation attempted: only .hs, .hsc or .lhs files are compiled)

```

**Comment by slotThe** [comment] 2021-03-11 18:07
On Thu, Mar 11 2021 09:49, V1V1D wrote:
>   font = "xft:mononoki-Regular Nerd Font Complete Mono:weight=bold:pixelsize=12:antialias=true:hinting=tr>

You're missing an ending " here

**Comment by vividsystem** [comment] 2021-03-12 06:24
Oh thx i din't notice that. So I fixed that! I noticed that without the Unicode Chars it works without error but when I get the same error again

**Comment by slotThe** [comment] 2021-03-12 07:42
On Thu, Mar 11 2021 22:24, V1V1D wrote:
> Oh thx i din't notice that. So I fixed that! I noticed that without
> the Unicode Chars it works without error but when I get the same error
> again

Mh interesting.  I don't quite recall how the parser is implemented,
perhaps try another unicode representation (decimal representations have
always worked for me)

**Comment by oogeek** [comment] 2021-04-02 08:35
I also encounter this error. It seems that it might be the change of parser. When I use xmobar-0.37 zip file from github, my config works fine. But today when I test it with git version of xmobar, it reports the same error.

**Comment by jaor** [comment] 2022-02-19 12:36
i think this is almost for sure caused by the missing dependency (we've seen similar error messages many times).  so i am closing the issue.  please feel free to re-open if that's not the case.

**Closed by jaor** 2022-02-19 12:36 UTC
